In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import warnings
warnings.filterwarnings("ignore")

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
data1 = pd.read_csv("/content/gdrive/My Drive/Dataset/UNSW_2018_IoT_Botnet_Full5pc_2.csv")

In [ ]:
data1.head()

   pkSeqID         stime flgs  ...  attack category  subcategory
0  1000001  1.528085e+09    e  ...       1      DoS          UDP
1  1000002  1.528085e+09    e  ...       1      DoS          UDP
2  1000003  1.528085e+09    e  ...       1      DoS          UDP
3  1000004  1.528085e+09    e  ...       1      DoS          UDP
4  1000005  1.528085e+09    e  ...       1      DoS          UDP

[5 rows x 46 columns]

In [ ]:
data2 = pd.read_csv("/content/gdrive/My Drive/Dataset/UNSW_2018_IoT_Botnet_Full5pc_4.csv")
data2.head()

   pkSeqID         stime flgs  ...  attack category  subcategory
0  3000001  1.528099e+09    e  ...       1     DDoS          UDP
1  3000002  1.528099e+09    e  ...       1     DDoS          UDP
2  3000003  1.528099e+09    e  ...       1     DDoS          UDP
3  3000004  1.528099e+09    e  ...       1     DDoS          UDP
4  3000005  1.528099e+09    e  ...       1     DDoS          UDP

[5 rows x 46 columns]

In [ ]:
data1.shape

(1000000, 46)

In [ ]:
data2.shape

(668522, 46)

In [ ]:
data = data1.append(data2)

In [ ]:
data.shape

(1668522, 46)

In [ ]:
data.head()

   pkSeqID         stime flgs  ...  attack category  subcategory
0  1000001  1.528085e+09    e  ...       1      DoS          UDP
1  1000002  1.528085e+09    e  ...       1      DoS          UDP
2  1000003  1.528085e+09    e  ...       1      DoS          UDP
3  1000004  1.528085e+09    e  ...       1      DoS          UDP
4  1000005  1.528085e+09    e  ...       1      DoS          UDP

[5 rows x 46 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1668522 entries, 0 to 668521
Data columns (total 46 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   pkSeqID                           1668522 non-null  int64
 1   stime                             1668522 non-null  float64
 2   flgs                              1668522 non-null  object
 3   flgs_number                       1668522 non-null  int64
 4   proto                             1668522 non-null  object
 5   proto_number                      1668522 non-null  int64
 6   saddr                             1668522 non-null  object
 7   sport                             1668522 non-null  object
 8   daddr                             1668522 non-null  object
 9   dport                             1668522 non-null  object
 10  pkts                              1668522 non-null  int64
 11  bytes                             1668522 non-null  int64
 12  state                             1668522 non-null  object
 13  state_number                      1668522 non-null  int64
 14  ltime                             1668522 non-null  float64
 15  seq                               1668522 non-null  int64
 16  dur                               1668522 non-null  float64
 17  mean                              1668522 non-null  float64
 18  stddev                            1668522 non-null  float64
 19  sum                               1668522 non-null  float64
 20  min                               1668522 non-null  float64
 21  max                               1668522 non-null  float64
 22  spkts                             1668522 non-null  int64
 23  dpkts                             1668522 non-null  int64
 24  sbytes                            1668522 non-null  int64
 25  dbytes                            1668522 non-null  int64
 26  rate                              1668522 non-null  float64
 27  srate                             1668522 non-null  float64
 28  drate                             1668522 non-null  float64
 29  TnBPSrcIP                         1668522 non-null  int64
 30  TnBPDstIP                         1668522 non-null  int64
 31  TnP_PSrcIP                        1668522 non-null  int64
 32  TnP_PDstIP                        1668522 non-null  int64
 33  TnP_PerProto                      1668522 non-null  int64
 34  TnP_Per_Dport                     1668522 non-null  int64
 35  AR_P_Proto_P_SrcIP                1668522 non-null  float64
 36  AR_P_Proto_P_DstIP                1668522 non-null  float64
 37  N_IN_Conn_P_DstIP                 1668522 non-null  int64
 38  N_IN_Conn_P_SrcIP                 1668522 non-null  int64
 39  AR_P_Proto_P_Sport                1668522 non-null  float64
 40  AR_P_Proto_P_Dport                1668522 non-null  float64
 41  Pkts_P_State_P_Protocol_P_DestIP  1668522 non-null  int64
 42  Pkts_P_State_P_Protocol_P_SrcIP   1668522 non-null  int64
 43  attack                            1668522 non-null  int64
 44  category                          1668522 non-null  object
 45  subcategory                       1668522 non-null  object
dtypes: float64(15), int64(22), object(9)
memory usage: 598.3+ MB

In [ ]:
data.isnull().sum()

pkSeqID                             0
stime                               0
flgs                                0
flgs_number                         0
proto                               0
proto_number                        0
saddr                               0
sport                               0
daddr                               0
dport                               0
pkts                                0
bytes                               0
state                               0
state_number                        0
ltime                               0
seq                                 0
dur                                 0
mean                                0
stddev                              0
sum                                 0
min                                 0
max                                 0
spkts                               0
dpkts                               0
sbytes                              0
dbytes                              0
rate                                0
srate                               0
drate                               0
TnBPSrcIP                           0
TnBPDstIP                           0
TnP_PSrcIP                          0
TnP_PDstIP                          0
TnP_PerProto                        0
TnP_Per_Dport                       0
AR_P_Proto_P_SrcIP                  0
AR_P_Proto_P_DstIP                  0
N_IN_Conn_P_DstIP                   0
N_IN_Conn_P_SrcIP                   0
AR_P_Proto_P_Sport                  0
AR_P_Proto_P_Dport                  0
Pkts_P_State_P_Protocol_P_DestIP    0
Pkts_P_State_P_Protocol_P_SrcIP     0
attack                              0
category                            0
subcategory                         0
dtype: int64

In [ ]:
data.drop(["pkSeqID","flgs","proto","state","attack"],axis=1,inplace=True)

In [ ]:
data.shape

(1668522, 41)

In [ ]:
data.dtypes[data.dtypes=='object']

saddr          object
sport          object
daddr          object
dport          object
category       object
subcategory    object
dtype: object

In [ ]:
data['saddr'].value_counts()

192.168.100.147              439157
192.168.100.150              412810
192.168.100.148              404693
192.168.100.149              400743
192.168.100.3                  5922
192.168.100.5                  5032
192.168.100.6                    42
192.168.100.7                    34
192.168.100.4                    19
192.168.100.1                    16
192.168.100.46                   15
192.168.100.27                   14
fe80::250:56ff:febe:254           6
fe80::c0c0:aa20:45b9:bdd9         4
192.168.100.55                    3
fe80::250:56ff:febe:c038          2
fe80::250:56ff:febe:e9d9          2
fe80::2c6a:ff9b:7e14:166a         2
fe80::250:56ff:febe:89ee          2
fe80::250:56ff:febe:26db          2
fe80::250:56ff:febe:bf1a          2
Name: saddr, dtype: int64

In [ ]:
data['sport'].value_counts()

0x0303    8934
80        1259
1589      1032
2290      1032
1822      1032
          ...
40413        1
62408        1
9821         1
11497        1
11868        1
Name: sport, Length: 121216, dtype: int64

In [ ]:
data['daddr'].value_counts()

192.168.100.3      1132026
192.168.100.5       199727
192.168.100.7       168814
192.168.100.6       156667
192.168.100.147       3136
                    ...
224.0.0.252              1
216.239.38.10            1
205.251.195.185          1
205.251.199.61           1
216.239.36.10            1
Name: daddr, Length: 84, dtype: int64

In [ ]:
data['subcategory'].value_counts()

UDP                  1227144
TCP                   348751
Service_Scan           73168
OS_Fingerprint         17914
HTTP                     989
Normal                   477
Keylogging                73
Data_Exfiltration          6
Name: subcategory, dtype: int64

In [ ]:
data['category'].value_counts()

DDoS              926624
DoS               650260
Reconnaissance     91082
Normal               477
Theft                 79
Name: category, dtype: int64

In [ ]:
data['sport'] = data['sport'].astype(str)
search_string='0x'
result = set([i for i in data['sport'] if i.startswith(search_string)])
result

{'0x0008', '0x000d', '0x0011', '0x0303'}

In [ ]:
data['sport']=data['sport'].replace(['0x5000'],'20480')
data['sport']=data['sport'].replace(['0x0303'],'771')
data['sport']=data['sport'].replace(['0x0008'],'8')
data['sport']=data['sport'].replace(['0x000d'],'13')
data['sport']=data['sport'].replace(['0x0011'],'17')
data["sport"] = data["sport"].astype(str).astype(int)

In [ ]:
data['dport'] = data['dport'].astype(str)
data['dport'] = data.dport.apply(lambda x: int(x,16) if len(x)>1 and x[1]=="x" else int(x))

In [ ]:
data.dtypes[data.dtypes=='object']

saddr          object
daddr          object
category       object
subcategory    object
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["saddr_enc"] = le.fit_transform(data.saddr)
data["daddr_enc"] = le.fit_transform(data.daddr)
data["category_enc"]= le.fit_transform(data.category)
data["subcategory_enc"]= le.fit_transform(data.subcategory)
data.drop(['saddr','daddr','category','subcategory'],axis=1,inplace=True)

In [ ]:
data.head()

          stime  flgs_number  ...  category_enc  subcategory_enc
0  1.528085e+09            1  ...             1                7
1  1.528085e+09            1  ...             1                7
2  1.528085e+09            1  ...             1                7
3  1.528085e+09            1  ...             1                7
4  1.528085e+09            1  ...             1                7

[5 rows x 41 columns]

In [ ]:
data['category_enc'].value_counts()

0    926624
1    650260
3     91082
2       477
4        79
Name: category_enc, dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1668522 entries, 0 to 668521
Data columns (total 41 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   stime                             1668522 non-null  float64
 1   flgs_number                       1668522 non-null  int64
 2   proto_number                      1668522 non-null  int64
 3   sport                             1668522 non-null  int64
 4   dport                             1668522 non-null  int64
 5   pkts                              1668522 non-null  int64
 6   bytes                             1668522 non-null  int64
 7   state_number                      1668522 non-null  int64
 8   ltime                             1668522 non-null  float64
 9   seq                               1668522 non-null  int64
 10  dur                               1668522 non-null  float64
 11  mean                              1668522 non-null  float64
 12  stddev                            1668522 non-null  float64
 13  sum                               1668522 non-null  float64
 14  min                               1668522 non-null  float64
 15  max                               1668522 non-null  float64
 16  spkts                             1668522 non-null  int64
 17  dpkts                             1668522 non-null  int64
 18  sbytes                            1668522 non-null  int64
 19  dbytes                            1668522 non-null  int64
 20  rate                              1668522 non-null  float64
 21  srate                             1668522 non-null  float64
 22  drate                             1668522 non-null  float64
 23  TnBPSrcIP                         1668522 non-null  int64
 24  TnBPDstIP                         1668522 non-null  int64
 25  TnP_PSrcIP                        1668522 non-null  int64
 26  TnP_PDstIP                        1668522 non-null  int64
 27  TnP_PerProto                      1668522 non-null  int64
 28  TnP_Per_Dport                     1668522 non-null  int64
 29  AR_P_Proto_P_SrcIP                1668522 non-null  float64
 30  AR_P_Proto_P_DstIP                1668522 non-null  float64
 31  N_IN_Conn_P_DstIP                 1668522 non-null  int64
 32  N_IN_Conn_P_SrcIP                 1668522 non-null  int64
 33  AR_P_Proto_P_Sport                1668522 non-null  float64
 34  AR_P_Proto_P_Dport                1668522 non-null  float64
 35  Pkts_P_State_P_Protocol_P_DestIP  1668522 non-null  int64
 36  Pkts_P_State_P_Protocol_P_SrcIP   1668522 non-null  int64
 37  saddr_enc                         1668522 non-null  int64
 38  daddr_enc                         1668522 non-null  int64
 39  category_enc                      1668522 non-null  int64
 40  subcategory_enc                   1668522 non-null  int64
dtypes: float64(15), int64(26)
memory usage: 534.7 MB

In [ ]:
data = data.sample(frac=0.5)
data

               stime  flgs_number  ...  category_enc  subcategory_enc
520037  1.528099e+09            1  ...             0                7
602683  1.526345e+09            6  ...             3                5
128908  1.528085e+09            1  ...             1                7
705703  1.528096e+09            2  ...             0                6
586340  1.528085e+09            1  ...             1                7
...              ...          ...  ...           ...              ...
252957  1.528099e+09            1  ...             0                7
562560  1.528099e+09            1  ...             0                7
330682  1.528099e+09            1  ...             0                7
552980  1.528085e+09            6  ...             1                7
947843  1.528096e+09            2  ...             0                6

[834261 rows x 41 columns]

In [ ]:
data['category_enc'].value_counts()

0    463263
1    325337
3     45400
2       218
4        43
Name: category_enc, dtype: int64

In [ ]:
y = data['category_enc']

In [ ]:
data.drop(["category_enc"],axis=1,inplace=True)

# **NORMALIZATION**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features = data.iloc[:,:-1]
cols = features.columns
scaled_features = scaler.fit_transform(features)
data = pd.DataFrame(scaled_features,columns = cols)

In [ ]:
data.head()

      stime  flgs_number  ...  saddr_enc  daddr_enc
0  0.256064    -0.284255  ...  -1.255025  -0.559839
1 -4.402405     6.160166  ...   0.408739  -0.559839
2  0.217798    -0.284255  ...   0.408739   0.461312
3  0.246386     1.004629  ...  -0.423143  -0.559839
4  0.217971    -0.284255  ...   0.408739   0.461312

[5 rows x 39 columns]

# **Splitting of Dataset into test and train set**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size = 0.2, random_state = 1)


import xgboost as xgboost
dtrain = xgboost.DMatrix(X_train, label=y_train)
dtest = xgboost.DMatrix(X_test, label=y_test)


from sklearn.metrics import mean_absolute_error
mean_train = np.mean(y_train)
baseline_predictions = np.ones(y_test.shape) * mean_train
mae_baseline = mean_absolute_error(y_test, baseline_predictions)
print("Baseline MAE is {:.2f}".format(mae_baseline))

Baseline MAE is 0.62

# **Calculation before Resampling**

In [ ]:
from xgboost import XGBClassifier
best_model = XGBClassifier()
best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)
predictions = [round(value) for value in y_pred]

In [ ]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from matplotlib import pyplot
y_pred = best_model.predict_proba(X_test)[:,1]
predictions = [round(value) for value in y_pred]

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE: %f" % (rmse))

RMSE: 0.702341

In [ ]:
accuracy = accuracy_score(y_test, predictions) 

print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 94.51%

# **Resampling**

# **sample_weight**

In [ ]:
from sklearn.utils import compute_sample_weight
sample_weight = compute_sample_weight('balanced', y_train)
sample_weight

array([0.35998468, 0.35998468, 0.51318155, ..., 0.35998468, 0.51318155,
       0.51318155])

In [ ]:
params_final = {
    'colsample_bytree': 1.0,
     'eta': 0.3,
     'eval_metric': 'mae',
     'max_depth': 9,
     'min_child_weight': 5,
     'objective': 'reg:squarederror',
     'subsample': 1.0
}

In [ ]:
best_model.set_params(**params_final)
best_model.fit(X_train, y_train,sample_weight=sample_weight)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1.0, eta=0.3,
              eval_metric='mae', gamma=0, learning_rate=0.1, max_delta_step=0,
              max_depth=9, min_child_weight=5, missing=None, n_estimators=100,
              n_jobs=1, nthread=None, objective='multi:softprob',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              seed=None, silent=None, subsample=1.0, verbosity=1)

In [ ]:
y_pred = best_model.predict(X_test)
predictions = [round(value) for value in y_pred]

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE: %f" % (rmse))

RMSE: 0.003462

In [ ]:
accuracy = accuracy_score(y_test, y_pred) 

print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 100.00%